# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - .git
    - bin
    - vendor
    - node_modules
    - var
    - gen
    - tmp
  skip-files:
    - \.pb\.go$
    - \.pb\.goclay\.go$

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    enable-all: true
    #check-shadowing: true
    #fieldalignment: true
  revive: # golint was replaced by revive
    min-confidence: 0
    rules:
      # Recommended in Revive docs
      # https://github.com/mgechev/revive#recommended-configuration
      - name: package-comments
        disabled: true
      - name: exported
        arguments:
          - disableStutteringCheck
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    # best practices: between 10 and 20, depending on the application domain
    min-complexity: 10

linters:
  disable-all: true
  enable:
    - revive # 'golint' is deprecated (since v1.41.0), replaced by revive
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - megacheck # (staticcheck + gosimple + unused in one linter)
    - depguard
    - unconvert
    - unparam
    - unused
    - nakedret
    - dupl

issues:
  exclude-use-default: false
  exclude:
    - is not allowed from list 'Main'
